### ISSUE TITLE
authentik email settings

### ISSUE THREAD

**Issue by Rawrnekton** [Rawrnekton/homelab#26]
i need to take a look at authentik email settings

i expect there to be a self-service password recovery of some sort
invites might need this too (though this might be an entirely separate issue)

**Comment by Rawrnekton** [comment]
possible snippets for helm chart values

```
global:
env:
   - name: AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME
     value: "false"
   - name: AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL
     value: "false"
   - name: AUTHENTIK_EMAIL__USERNAME
     valueFrom:
       secretKeyRef:
         name: authentik-secret
         key: email-username
   - name: AUTHENTIK_EMAIL__PASSWORD
     valueFrom:
       secretKeyRef:
         name: authentik-secret
         key: email-password
``` 

```
email:
   from: from@example.com
   host: mail.example.com
   port: 587
   use_tls: true
```
